#!/usr/bin/env python
#
# Copyright (C) 2008 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
import os
import g9_common as common

LOCAL_DIR = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
RELEASETOOLS_DIR = os.path.abspath(os.path.join(LOCAL_DIR, '../../../build/tools/releasetools'))
TARGET_DIR = os.getenv('OUT')
UTILITIES_DIR = os.path.join(TARGET_DIR, 'utilities')
# Add releasetools directory to python path
sys.path.append(RELEASETOOLS_DIR)

# Import the existing file so we just have to rewrite the modules we need.
# This is a nasty hack as the filename doesn't end in .py, but it works
filename = os.path.join(RELEASETOOLS_DIR, "ota_from_target_files")
ota_from_target_files = common.load_module_from_file('ota_from_target_files', filename)

from ota_from_target_files import *
import g9_edify_generator as edify_generator

__doc__ = ota_from_target_files.__doc__
def AddUtilities(output_zip):


    output_zip.write(os.path.join(UTILITIES_DIR, "busybox"), "busybox")
    output_zip.write(os.path.join(UTILITIES_DIR, "abcbox"), "abcbox")
    output_zip.write(os.path.join(UTILITIES_DIR, "make_ext4fs"), "make_ext4fs")
    
    output_zip.write(os.path.join(TARGET_DIR, "kernel"), "kernel")
    output_zip.write(os.path.join(TARGET_DIR, "ramdisk.img"), "ramdisk.img")
    
    
    
    
    #script.AppendExtra('if (!is_mounted("/mnt/rawfs")) then')
    #script.AppendExtra('ui_print("mounting rawfs");')
    #script.AppendExtra('assert(run_program("/tmp/utils/mount","-trawfs", "/dev/block/mmcblk0p1", "/mnt/rawfs"));')
    #script.AppendExtra('endif;')
    
    #script.AppendExtra('ui_print("*****        FLASHING BOOT IMAGE        *****");')
    #script.AppendExtra('package_extract_file("kernel", "/tmp/kernel");')
    #script.AppendExtra('package_extract_file("ramdisk.img", "/tmp/ramdisk.img");')
    #script.AppendExtra('assert(run_program("/tmp/utils/kd_flasher","-i", "/tmp/ramdisk.img", "-k" , "/tmp/kernel" ));')
    #script.AppendExtra('ui_print("*****               DONE                *****");')
    #script.AppendExtra('ui_print("");')
    #script.AppendExtra('ui_print("*****        INSTALLING SYSTEM          *****");')
    
    
def WriteFullOTAPackage(input_zip, output_zip):
  # TODO: how to determine this?  We don't know what version it will
  # be installed on top of.  For now, we expect the API just won't
  # change very often.
  OPTIONS.verbose = True
  
  script = edify_generator.EdifyGenerator(3, OPTIONS.info_dict)

  metadata = {"post-build": GetBuildProp("ro.build.fingerprint",
                                         OPTIONS.info_dict),
              "pre-device": GetBuildProp("ro.build.product",
                                         OPTIONS.info_dict),
              "post-timestamp": GetBuildProp("ro.build.date.utc",
                                             OPTIONS.info_dict),
              }

  
  AddUtilities(output_zip)
  script.UnpackPackageTools("busybox")
  script.UnpackPackageTools("abcbox")
  script.UnpackPackageTools("make_ext4fs")
  
  if OPTIONS.backuptool:
    script.Mount("/system")
    script.RunBackup("backup")
    script.Unmount("/system")

  script.ShowProgress(0.5, 0)

  if OPTIONS.wipe_user_data:
    script.FormatPartition("/data")

  script.Unmount("/system")
  script.FormatPartition("/system")
  script.Mount("/system")
  script.UnpackPackageDir("recovery", "/system")
  script.UnpackPackageDir("system", "/system")

  symlinks = CopySystemFiles(input_zip, output_zip)
  script.MakeSymlinks(symlinks)

  Item.GetMetadata(input_zip)
  Item.Get("system").SetPermissions(script)

  script.ShowProgress(0.2, 0)

  if OPTIONS.backuptool:
    script.ShowProgress(0.2, 10)
    script.RunBackup("restore")

  script.ShowProgress(0.2, 10)

  script.ShowProgress(0.1, 0)

  if OPTIONS.extra_script is not None:
    script.AppendExtra(OPTIONS.extra_script)

  script.UnmountAll()
  script.AddToZip(input_zip, output_zip)
  WriteMetadata(metadata, output_zip)
ota_from_target_files.WriteFullOTAPackage = WriteFullOTAPackage


def WriteIncrementalOTAPackage(target_zip, source_zip, output_zip):
    print "Incremental OTA Packages are not support on the g9 at this time"
    sys.exit(1)
ota_from_target_files.WriteIncrementalOTAPackage = WriteIncrementalOTAPackage

if __name__ == '__main__':
  try:
    main(sys.argv[1:])
  except common.ExternalError, e:
    print
    print "   ERROR: %s" % (e,)
    print
    sys.exit(1)
